version: '3.9'
services:
  postgres:
    image: postgres:16.
    container_name: postgresdb
    networks:
      - appnet
    environment:
      - POSTGRES_DB=curr_data
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=myPas!w0rd
    ports: -"5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  currapp:
    image: currapp
    networks:
      - appnet
    depends_on:
      - postgres
